-- Librería global de ejercicios (lectura pública, sin auth)
create table if not exists exercises_library (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  muscle_group text not null,
  description text,
  created_at timestamptz default now()
);

alter table exercises_library enable row level security;
create policy "Public read" on exercises_library for select using (true);

-- ── PECHO ─────────────────────────────────────────────────────────────
insert into exercises_library (name, muscle_group, description) values
('Press de banca con barra', 'Pecho', 'Empuje horizontal en banco plano con barra libre'),
('Press de banca con mancuernas', 'Pecho', 'Igual que el anterior pero con mancuernas, mayor rango de movimiento'),
('Press de banca en Smith', 'Pecho', 'Empuje horizontal en banco plano con máquina Smith'),
('Press inclinado con barra', 'Pecho', 'Empuje en banco inclinado, énfasis en pecho superior'),
('Press inclinado con mancuernas', 'Pecho', 'Igual que el anterior con mancuernas'),
('Press inclinado en Smith', 'Pecho', 'Empuje en banco inclinado con máquina Smith'),
('Press declinado con barra', 'Pecho', 'Empuje en banco declinado, énfasis en pecho inferior'),
('Press declinado con mancuernas', 'Pecho', 'Igual que el anterior con mancuernas'),
('Aperturas con mancuernas plano', 'Pecho', 'Movimiento de apertura y cierre en banco plano'),
('Aperturas inclinadas con mancuernas', 'Pecho', 'Aperturas en banco inclinado, más pecho superior'),
('Crossover en polea alta', 'Pecho', 'Jale de poleas altas hacia el centro, énfasis en pecho inferior'),
('Crossover en polea baja', 'Pecho', 'Jale de poleas bajas hacia arriba, énfasis en pecho superior'),
('Crossover en polea media', 'Pecho', 'Jale de poleas a la altura del pecho, activación media'),
('Press en máquina pecho', 'Pecho', 'Empuje horizontal en máquina guiada'),
('Press en máquina inclinado', 'Pecho', 'Empuje en máquina con ángulo inclinado'),
('Pec deck / Mariposa', 'Pecho', 'Máquina de aperturas con codos semiflexionados'),
('Fondos en paralelas', 'Pecho', 'Bajada y subida del cuerpo entre barras, énfasis pecho si el torso va inclinado'),
('Flexiones', 'Pecho', 'Empuje con peso corporal en el suelo'),
('Flexiones inclinadas', 'Pecho', 'Push-up con pies elevados, énfasis en pecho superior'),
('Flexiones declinadas', 'Pecho', 'Push-up con manos elevadas, énfasis en pecho inferior'),
('Flexiones diamante', 'Pecho', 'Push-up con manos juntas, mayor énfasis en tríceps y pecho interno'),
('Pull-over en polea', 'Pecho', 'Bajada del cable desde arriba con brazos extendidos, estira y activa pecho'),

-- ── ESPALDA ───────────────────────────────────────────────────────────
('Dominadas agarre prono', 'Espalda', 'Jale del peso corporal con agarre ancho y palmas hacia afuera'),
('Dominadas agarre supino', 'Espalda', 'Jale del peso corporal con agarre cerrado y palmas hacia adentro'),
('Jalón al pecho en polea alta', 'Espalda', 'Jale de barra desde polea alta hacia el pecho, agarre ancho'),
('Jalón al pecho agarre cerrado', 'Espalda', 'Jale de polea alta con agarre neutro y cerrado'),
('Jalón en polea alta agarre supino', 'Espalda', 'Jale con palmas mirando hacia el cuerpo, más bíceps'),
('Remo con barra', 'Espalda', 'Jale de barra desde el suelo con torso inclinado'),
('Remo con mancuerna unilateral', 'Espalda', 'Jale de mancuerna apoyando la rodilla en banco'),
('Remo en máquina', 'Espalda', 'Jale horizontal en máquina guiada, pecho apoyado'),
('Remo en polea baja', 'Espalda', 'Jale horizontal con cable sentado, agarre neutro o prono'),
('Remo en polea baja agarre ancho', 'Espalda', 'Mismo movimiento con barra y agarre más abierto'),
('Remo T-bar', 'Espalda', 'Jale con barra anclada en un extremo y peso en el otro'),
('Remo T-bar con pecho apoyado', 'Espalda', 'Igual que el anterior con soporte para el pecho'),
('Remo en Smith', 'Espalda', 'Jale horizontal con máquina Smith, torso inclinado'),
('Pullover en polea alta', 'Espalda', 'Jale del cable desde arriba con brazos extendidos, activa dorsal'),
('Straight-arm pulldown', 'Espalda', 'Jale de polea alta con brazos rectos hacia abajo, aísla el dorsal'),
('Face pull en polea', 'Espalda', 'Jale de cuerda hacia la cara, activa trapecio medio y romboides'),
('Encogimientos con barra', 'Espalda', 'Elevación de hombros con barra, énfasis en trapecio superior'),
('Encogimientos con mancuernas', 'Espalda', 'Igual que el anterior con mancuernas'),
('Encogimientos en máquina', 'Espalda', 'Elevación de hombros en máquina guiada'),
('Hiperextensiones en banco', 'Espalda', 'Extensión del torso boca abajo, activa erector y glúteo'),
('Buenos días', 'Espalda', 'Bisagra de cadera con barra en la espalda, erector y dorsales'),
('Superman', 'Espalda', 'Extensión simultánea de brazos y piernas boca abajo en el suelo'),
('Remo invertido', 'Espalda', 'Remo con barra fija a la altura de la cadera, peso corporal'),

-- ── HOMBRO ────────────────────────────────────────────────────────────
('Press militar con barra de pie', 'Hombro', 'Empuje vertical con barra desde el pecho hacia arriba, de pie'),
('Press militar con barra sentado', 'Hombro', 'Igual que el anterior sentado, más estabilidad'),
('Press militar con mancuernas de pie', 'Hombro', 'Empuje vertical con mancuernas de pie'),
('Press militar con mancuernas sentado', 'Hombro', 'Empuje vertical con mancuernas sentado'),
('Press en máquina de hombro', 'Hombro', 'Empuje vertical en máquina guiada'),
('Press en Smith hombro', 'Hombro', 'Empuje vertical con máquina Smith sentado'),
('Elevaciones laterales con mancuernas', 'Hombro', 'Elevación de brazos al lado hasta la altura del hombro, deltoides lateral'),
('Elevaciones laterales en polea baja', 'Hombro', 'Igual que el anterior con cable, tensión constante'),
('Elevaciones laterales en máquina', 'Hombro', 'Elevación lateral en máquina guiada'),
('Elevaciones frontales con mancuernas', 'Hombro', 'Elevación de brazos al frente, deltoides anterior'),
('Elevaciones frontales con barra', 'Hombro', 'Igual que el anterior con barra'),
('Elevaciones frontales en polea baja', 'Hombro', 'Elevación frontal con cable, tensión constante'),
('Press landmine', 'Hombro', 'Empuje diagonal con barra anclada, mezcla de frontal y vertical'),

-- ── BÍCEPS ────────────────────────────────────────────────────────────
('Curl con barra recta', 'Bíceps', 'Flexión de codo con barra, agarre supino'),
('Curl con barra EZ', 'Bíceps', 'Igual que el anterior con barra EZ, menos estrés en muñeca'),
('Curl con mancuernas de pie', 'Bíceps', 'Flexión de codo alternada o simultánea con mancuernas'),
('Curl con mancuernas sentado', 'Bíceps', 'Igual que el anterior sentado, menos impulso'),
('Curl martillo', 'Bíceps', 'Flexión con agarre neutro, activa braquial y braquiorradial'),
('Curl en polea baja', 'Bíceps', 'Flexión de codo con cable, tensión constante'),
('Curl en polea alta', 'Bíceps', 'Flexión con cable desde arriba, pico de contracción diferente'),
('Curl en máquina', 'Bíceps', 'Flexión en máquina guiada'),
('Curl predicador con barra EZ', 'Bíceps', 'Flexión apoyando los tríceps en banco predicador, elimina impulso'),
('Curl predicador con mancuerna', 'Bíceps', 'Igual que el anterior unilateral'),
('Curl inclinado con mancuernas', 'Bíceps', 'Sentado en banco inclinado, mayor estiramiento del bíceps'),

-- ── TRÍCEPS ───────────────────────────────────────────────────────────
('Press francés con barra EZ tumbado', 'Tríceps', 'Flexión y extensión de codo con barra EZ sobre la cabeza, tumbado'),
('Press francés con mancuerna tumbado', 'Tríceps', 'Igual que el anterior con mancuerna'),
('Press francés con mancuernas sentado', 'Tríceps', 'Extensión sobre la cabeza sentado, estiramiento máximo'),
('Extensión en polea alta con cuerda', 'Tríceps', 'Empuje hacia abajo con cuerda desde polea alta'),
('Extensión en polea alta con barra', 'Tríceps', 'Igual que el anterior con barra recta o EZ'),
('Extensión en polea baja', 'Tríceps', 'Empuje hacia arriba desde polea baja, énfasis diferente'),
('Fondos en paralelas tríceps', 'Tríceps', 'Bajada y subida entre barras con torso vertical, énfasis en tríceps'),
('Fondos en banco', 'Tríceps', 'Manos apoyadas en banco detrás, baja y sube con el cuerpo'),
('Press cerrado con barra', 'Tríceps', 'Press de banca con agarre cerrado, énfasis en tríceps'),
('Press cerrado en Smith', 'Tríceps', 'Igual que el anterior en máquina Smith'),
('Extensión unilateral en polea', 'Tríceps', 'Extensión de un brazo con cable, más control y rango'),
('Skull crusher con barra EZ', 'Tríceps', 'Baja la barra hacia la frente tumbado, extensión de codo'),
('Skull crusher con mancuernas', 'Tríceps', 'Igual que el anterior con mancuernas'),
('Katanas en polea baja', 'Tríceps', 'Desde polea baja con agarre cruzado, extensión hacia arriba simulando sacar dos espadas'),

-- ── CORE ──────────────────────────────────────────────────────────────
('Plancha frontal', 'Core', 'Posición isométrica apoyado en antebrazos y puntas de pie'),
('Plancha lateral', 'Core', 'Isométrico lateral apoyado en un antebrazo, activa oblicuos'),
('Plancha con elevación de brazo', 'Core', 'Plancha frontal levantando un brazo alternado, más inestabilidad'),
('Crunch tradicional', 'Core', 'Flexión parcial del torso tumbado, énfasis en recto abdominal'),
('Crunch en polea', 'Core', 'Flexión del torso desde polea alta con cuerda arrodillado'),
('Crunch inverso', 'Core', 'Eleva las caderas desde el suelo con piernas semiflexionadas'),
('Sit-up', 'Core', 'Flexión completa del torso hasta sentarse, rango completo'),
('Elevación de piernas tumbado', 'Core', 'Sube las piernas rectas desde el suelo, énfasis en abdomen inferior'),
('Elevación de piernas en barra', 'Core', 'Colgado de barra, sube las piernas rectas o flexionadas'),
('Rodillas al pecho en barra', 'Core', 'Colgado de barra, lleva las rodillas hacia el pecho'),
('Dragon flag', 'Core', 'Tumbado en banco, sube y baja el cuerpo rígido apoyando solo los hombros'),
('Ab wheel', 'Core', 'Rodando la rueda hacia adelante desde rodillas, extensión del core'),
('Pallof press', 'Core', 'Empuje de cable al frente resistiendo la rotación, anti-rotación'),
('Russian twist', 'Core', 'Rotación del torso con peso sentado, pies elevados'),
('Woodchop en polea alta', 'Core', 'Jale diagonal de cable de arriba hacia abajo, rotación del tronco'),
('Woodchop en polea baja', 'Core', 'Jale diagonal de cable de abajo hacia arriba, rotación del tronco'),
('Dead bug', 'Core', 'Tumbado, extiende brazo y pierna opuesta alternados manteniendo la espalda pegada al suelo'),
('Bird dog', 'Core', 'En cuadrupedia, extiende brazo y pierna opuesta, control lumbar'),
('Mountain climbers', 'Core', 'En posición de plancha, lleva las rodillas al pecho de forma alternada y rápida'),
('Hollow body hold', 'Core', 'Tumbado, mantén brazos y piernas elevados con la zona lumbar pegada al suelo'),
('Suitcase carry', 'Core', 'Caminar cargando peso en un solo lado, anti-flexión lateral'),
('Farmer carry', 'Core', 'Caminar con peso en ambas manos, estabilidad total del core'),

-- ── PIERNA ────────────────────────────────────────────────────────────
('Sentadilla con barra', 'Pierna', 'Barra en la espalda, descenso hasta paralelo o más, cuádriceps y glúteo'),
('Sentadilla frontal', 'Pierna', 'Barra apoyada en los hombros al frente, más cuádriceps y core'),
('Sentadilla en Smith', 'Pierna', 'Sentadilla con máquina Smith, más control de la trayectoria'),
('Sentadilla goblet', 'Pierna', 'Sosteniendo una mancuerna al pecho, buena para técnica'),
('Sentadilla hack con barra', 'Pierna', 'Barra detrás de las piernas, énfasis en cuádriceps'),
('Hack squat en máquina', 'Pierna', 'Máquina inclinada de sentadilla, énfasis en cuádriceps'),
('Prensa de pierna', 'Pierna', 'Empuje de plataforma con los pies, cuádriceps y glúteo'),
('Prensa de pierna unilateral', 'Pierna', 'Igual que la anterior con una sola pierna'),
('Extensión de cuádriceps en máquina', 'Pierna', 'Extensión de rodilla sentado en máquina, aísla el cuádriceps'),
('Extensión de cuádriceps unilateral', 'Pierna', 'Igual que el anterior con una sola pierna, más control y simetría'),
('Curl femoral tumbado', 'Pierna', 'Flexión de rodilla tumbado en máquina, aísla los isquiotibiales'),
('Curl femoral sentado', 'Pierna', 'Flexión de rodilla sentado en máquina, énfasis diferente al tumbado'),
('Curl femoral de pie', 'Pierna', 'Flexión de rodilla de pie unilateral en máquina'),
('Peso muerto rumano', 'Pierna', 'Bisagra de cadera con rodillas semiflexionadas, isquiotibiales y dorsal bajo'),
('Peso muerto piernas rígidas', 'Pierna', 'Bisagra sin flexión de rodilla, máximo estiramiento de isquiotibiales'),
('Zancada con mancuernas', 'Pierna', 'Paso largo hacia adelante bajando la rodilla trasera, cuádriceps y glúteo'),
('Zancada con barra', 'Pierna', 'Igual que la anterior con barra en la espalda'),
('Zancada inversa', 'Pierna', 'Paso hacia atrás en lugar de adelante, menos estrés en rodilla'),
('Zancada búlgara', 'Pierna', 'Pie trasero elevado en banco, cuádriceps y glúteo unilateral'),
('Step-up con mancuernas', 'Pierna', 'Subir un escalón o banco con mancuernas, unilateral'),
('Hip thrust con barra', 'Pierna', 'Cadera apoyada en banco, empuje vertical con barra, glúteo máximo'),
('Hip thrust en máquina', 'Pierna', 'Igual que el anterior en máquina guiada'),
('Glute bridge', 'Pierna', 'Igual que el hip thrust pero en el suelo, variante más accesible'),
('Patada de glúteo en polea', 'Pierna', 'De pie o en cuadrupedia, extensión de cadera con cable, aísla el glúteo'),
('Abducción en máquina', 'Pierna', 'Apertura de piernas sentado en máquina, glúteo medio'),
('Aducción en máquina', 'Pierna', 'Cierre de piernas sentado en máquina, aductores'),
('Elevación de talones de pie', 'Pierna', 'Elevación en punta de pie de pie, gemelos'),
('Elevación de talones sentado', 'Pierna', 'Igual que el anterior sentado, énfasis en sóleo'),
('Elevación de talones en prensa', 'Pierna', 'Calf raise usando la plataforma de la prensa'),
('Nordic curl', 'Pierna', 'Anclado de tobillos, baja el torso con los isquiotibiales, muy exigente'),
('Sissy squat', 'Pierna', 'Rodillas hacia adelante con talones elevados, aísla el cuádriceps');
