-- =============================================================================
-- CURACIÓN COMPLETA DE exercises_library (136 ejercicios)
-- =============================================================================
-- Rellena las columnas de enriquecimiento añadidas por
-- exercises_library_coaching_migration.sql. Una sentencia UPDATE por ejercicio,
-- agrupadas por muscle_group. Fuente de verdad del motor de recomendaciones
-- (src/lib/engine/).
--
-- VOCABULARIO (el motor depende de estos valores exactos):
--   category           push | pull | legs | core
--   movement_pattern   horizontal_push incline_push dip chest_iso vertical_push
--                      lateral_raise front_raise vertical_pull horizontal_pull
--                      rear_delt shrug back_extension hinge squat lunge
--                      hip_extension leg_curl_iso quad_iso adduction abduction
--                      calf_raise curl triceps_extension core_anti_extension
--                      core_flexion core_rotation core_carry
--   primary/secondary_muscles  ⊆ MUSCLE_GROUPS (src/lib/muscleGroups.js):
--                      Pecho Espalda Hombro Bíceps Tríceps Core Cuádriceps
--                      Hamstrings Glúteo Gemelos.  primary_muscles[1] = muscle_group.
--   equipment          barra mancuerna polea maquina smith peso_corporal banco
--                      barra_dominadas rueda_abs
--                      (disponible ⟺ equipment ⊆ equipo del usuario)
--   difficulty         nivel MÍNIMO: Principiante | Intermedio | Avanzado
--   tracking_type      weight_reps | reps | time
--   substitution_group familia intercambiable (dedup en el día + fallback 1RM)
--   best_rep_min/max   rango efectivo del ejercicio (segundos si tracking=time)
--   coaching_notes     una indicación técnica corta (se muestra en el plan)
-- =============================================================================

-- ── PECHO ────────────────────────────────────────────────────────────────────
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps,Hombro}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='press_plano', best_rep_min=5, best_rep_max=10, coaching_notes='Escápulas retraídas y pies firmes; baja la barra con control al pecho medio.' where name='Press de banca con barra';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps,Hombro}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_plano', best_rep_min=6, best_rep_max=12, coaching_notes='Mayor rango que con barra; no choques las mancuernas arriba.' where name='Press de banca con mancuernas';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps,Hombro}', equipment='{smith,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_plano', best_rep_min=6, best_rep_max=12, coaching_notes='Coloca el banco para que la barra baje al pecho medio; trayectoria guiada, ideal para acercarte al fallo.' where name='Press de banca en Smith';
update exercises_library set category='push', movement_pattern='incline_push', primary_muscles='{Pecho}', secondary_muscles='{Hombro,Tríceps}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='press_inclinado', best_rep_min=6, best_rep_max=10, coaching_notes='Banco a 30-45 grados; énfasis en pecho superior.' where name='Press inclinado con barra';
update exercises_library set category='push', movement_pattern='incline_push', primary_muscles='{Pecho}', secondary_muscles='{Hombro,Tríceps}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_inclinado', best_rep_min=8, best_rep_max=12, coaching_notes='Baja profundo con control; el estiramiento del pecho superior es la parte valiosa.' where name='Press inclinado con mancuernas';
update exercises_library set category='push', movement_pattern='incline_push', primary_muscles='{Pecho}', secondary_muscles='{Hombro,Tríceps}', equipment='{smith,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_inclinado', best_rep_min=8, best_rep_max=12, coaching_notes='Guiado y estable; útil para progresar cargas en inclinado sin banquero.' where name='Press inclinado en Smith';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='press_declinado', best_rep_min=6, best_rep_max=10, coaching_notes='Recorrido corto y fuerte; énfasis en pecho inferior.' where name='Press declinado con barra';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_declinado', best_rep_min=8, best_rep_max=12, coaching_notes='Controla la bajada; no rebotes en el pecho.' where name='Press declinado con mancuernas';
update exercises_library set category='push', movement_pattern='chest_iso', primary_muscles='{Pecho}', secondary_muscles='{Hombro}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='aperturas_cruce', best_rep_min=10, best_rep_max=15, coaching_notes='Codos semiflexionados fijos; abre hasta sentir el estiramiento, sin dolor de hombro.' where name='Aperturas con mancuernas plano';
update exercises_library set category='push', movement_pattern='chest_iso', primary_muscles='{Pecho}', secondary_muscles='{Hombro}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='aperturas_cruce', best_rep_min=10, best_rep_max=15, coaching_notes='En banco inclinado; el pecho superior trabaja más en el estiramiento.' where name='Aperturas inclinadas con mancuernas';
update exercises_library set category='push', movement_pattern='chest_iso', primary_muscles='{Pecho}', secondary_muscles='{Hombro}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='aperturas_cruce', best_rep_min=10, best_rep_max=15, coaching_notes='Cruza abajo y aprieta un segundo; tensión constante del cable.' where name='Crossover en polea alta';
update exercises_library set category='push', movement_pattern='chest_iso', primary_muscles='{Pecho}', secondary_muscles='{Hombro}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='aperturas_cruce', best_rep_min=10, best_rep_max=15, coaching_notes='De abajo hacia arriba; énfasis en pecho superior.' where name='Crossover en polea baja';
update exercises_library set category='push', movement_pattern='chest_iso', primary_muscles='{Pecho}', secondary_muscles='{Hombro}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='aperturas_cruce', best_rep_min=10, best_rep_max=15, coaching_notes='Poleas a la altura del pecho; activación media y uniforme.' where name='Crossover en polea media';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps,Hombro}', equipment='{maquina}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_plano', best_rep_min=8, best_rep_max=12, coaching_notes='Ajusta el asiento para que las manos queden a la altura del pecho.' where name='Press en máquina pecho';
update exercises_library set category='push', movement_pattern='incline_push', primary_muscles='{Pecho}', secondary_muscles='{Hombro,Tríceps}', equipment='{maquina}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_inclinado', best_rep_min=8, best_rep_max=12, coaching_notes='Empuja sin bloquear codos del todo; mantén la tensión.' where name='Press en máquina inclinado';
update exercises_library set category='push', movement_pattern='chest_iso', primary_muscles='{Pecho}', secondary_muscles='{Hombro}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='aperturas_cruce', best_rep_min=10, best_rep_max=15, coaching_notes='Codos semiflexionados; junta y aprieta un segundo al centro.' where name='Pec deck / Mariposa';
update exercises_library set category='push', movement_pattern='dip', primary_muscles='{Pecho}', secondary_muscles='{Tríceps,Hombro}', equipment='{peso_corporal,barra_dominadas}', difficulty='Intermedio', is_compound=true, tracking_type='reps', substitution_group='fondos', best_rep_min=6, best_rep_max=12, coaching_notes='Inclina el torso hacia delante para cargar el pecho; baja hasta estirar sin dolor.' where name='Fondos en paralelas';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps,Hombro,Core}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=true, tracking_type='reps', substitution_group='press_plano', best_rep_min=8, best_rep_max=20, coaching_notes='Cuerpo en línea recta; el core no se hunde.' where name='Flexiones';
update exercises_library set category='push', movement_pattern='incline_push', primary_muscles='{Pecho}', secondary_muscles='{Hombro,Tríceps,Core}', equipment='{peso_corporal,banco}', difficulty='Intermedio', is_compound=true, tracking_type='reps', substitution_group='press_inclinado', best_rep_min=8, best_rep_max=20, coaching_notes='Pies elevados; más carga en pecho superior y hombro.' where name='Flexiones inclinadas';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps,Hombro}', equipment='{peso_corporal,banco}', difficulty='Principiante', is_compound=true, tracking_type='reps', substitution_group='press_plano', best_rep_min=10, best_rep_max=20, coaching_notes='Manos elevadas; versión más accesible, ideal para acumular reps limpias.' where name='Flexiones declinadas';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Pecho}', secondary_muscles='{Tríceps}', equipment='{peso_corporal}', difficulty='Intermedio', is_compound=true, tracking_type='reps', substitution_group='press_cerrado', best_rep_min=8, best_rep_max=15, coaching_notes='Manos juntas bajo el pecho; codos pegados al torso.' where name='Flexiones diamante';
update exercises_library set category='push', movement_pattern='chest_iso', primary_muscles='{Pecho}', secondary_muscles='{Espalda}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='pullover_pecho', best_rep_min=10, best_rep_max=15, coaching_notes='Brazos casi rectos; lleva el cable en arco amplio sintiendo el estiramiento del pecho.' where name='Pull-over en polea';

-- ── ESPALDA ──────────────────────────────────────────────────────────────────
update exercises_library set category='pull', movement_pattern='vertical_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{peso_corporal,barra_dominadas}', difficulty='Intermedio', is_compound=true, tracking_type='reps', substitution_group='dominadas', best_rep_min=5, best_rep_max=12, coaching_notes='Inicia bajando las escápulas; pecho hacia la barra, sin balanceo.' where name='Dominadas agarre prono';
update exercises_library set category='pull', movement_pattern='vertical_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{peso_corporal,barra_dominadas}', difficulty='Intermedio', is_compound=true, tracking_type='reps', substitution_group='dominadas', best_rep_min=5, best_rep_max=12, coaching_notes='Agarre supino: más bíceps; controla la bajada completa.' where name='Dominadas agarre supino';
update exercises_library set category='pull', movement_pattern='vertical_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{polea}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='jalon_vertical', best_rep_min=8, best_rep_max=12, coaching_notes='Lleva la barra a la clavícula con el pecho alto; no te recuestes en exceso.' where name='Jalón al pecho en polea alta';
update exercises_library set category='pull', movement_pattern='vertical_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{polea}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='jalon_vertical', best_rep_min=8, best_rep_max=12, coaching_notes='Agarre neutro cerrado; codos hacia las costillas.' where name='Jalón al pecho agarre cerrado';
update exercises_library set category='pull', movement_pattern='vertical_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{polea}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='jalon_vertical', best_rep_min=8, best_rep_max=12, coaching_notes='Palmas hacia ti; el bíceps ayuda más, buen puente hacia las dominadas.' where name='Jalón en polea alta agarre supino';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps,Hombro}', equipment='{barra}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=6, best_rep_max=10, coaching_notes='Torso a 45 grados y espalda neutra; jala hacia el abdomen, no al pecho.' where name='Remo con barra';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=8, best_rep_max=12, coaching_notes='Rodilla y mano en el banco; jala con el codo pegado, sin rotar el torso.' where name='Remo con mancuerna unilateral';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{maquina}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=8, best_rep_max=12, coaching_notes='Pecho apoyado; elimina el impulso y aísla el jalón.' where name='Remo en máquina';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{polea}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=8, best_rep_max=12, coaching_notes='Torso erguido y estable; lleva el agarre al ombligo.' where name='Remo en polea baja';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps,Hombro}', equipment='{polea}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=8, best_rep_max=12, coaching_notes='Agarre ancho: codos más abiertos, más espalda alta.' where name='Remo en polea baja agarre ancho';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{barra}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=6, best_rep_max=10, coaching_notes='Cadera atrás, espalda neutra; carga pesado sin perder la postura.' where name='Remo T-bar';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{maquina}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=8, best_rep_max=12, coaching_notes='El apoyo del pecho quita la fatiga lumbar; concéntrate en juntar las escápulas.' where name='Remo T-bar con pecho apoyado';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps}', equipment='{smith}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='remo_horizontal', best_rep_min=8, best_rep_max=12, coaching_notes='Trayectoria fija; mantén el ángulo del torso constante toda la serie.' where name='Remo en Smith';
update exercises_library set category='pull', movement_pattern='horizontal_pull', primary_muscles='{Espalda}', secondary_muscles='{Bíceps,Core}', equipment='{peso_corporal,barra}', difficulty='Principiante', is_compound=true, tracking_type='reps', substitution_group='remo_horizontal', best_rep_min=8, best_rep_max=15, coaching_notes='Cuerpo en tabla bajo la barra; pecho a la barra en cada rep.' where name='Remo invertido';
update exercises_library set category='pull', movement_pattern='vertical_pull', primary_muscles='{Espalda}', secondary_muscles='{Tríceps}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='pullover_dorsal', best_rep_min=10, best_rep_max=15, coaching_notes='Brazos casi rectos; siente el dorsal tirando desde arriba.' where name='Pullover en polea alta';
update exercises_library set category='pull', movement_pattern='vertical_pull', primary_muscles='{Espalda}', secondary_muscles='{Tríceps}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='pullover_dorsal', best_rep_min=10, best_rep_max=15, coaching_notes='Empuja el cable hacia el muslo con brazos rectos; aísla el dorsal.' where name='Straight-arm pulldown';
update exercises_library set category='pull', movement_pattern='rear_delt', primary_muscles='{Espalda}', secondary_muscles='{Hombro}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='face_pull', best_rep_min=12, best_rep_max=20, coaching_notes='Jala la cuerda hacia la cara con codos altos; salud de hombro en cada plan.' where name='Face pull en polea';
update exercises_library set category='pull', movement_pattern='shrug', primary_muscles='{Espalda}', secondary_muscles='{Hombro}', equipment='{barra}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='encogimientos', best_rep_min=10, best_rep_max=15, coaching_notes='Sube los hombros recto hacia las orejas; pausa arriba, sin rotar.' where name='Encogimientos con barra';
update exercises_library set category='pull', movement_pattern='shrug', primary_muscles='{Espalda}', secondary_muscles='{Hombro}', equipment='{mancuerna}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='encogimientos', best_rep_min=10, best_rep_max=15, coaching_notes='Brazos relajados a los lados; solo suben los hombros.' where name='Encogimientos con mancuernas';
update exercises_library set category='pull', movement_pattern='shrug', primary_muscles='{Espalda}', secondary_muscles='{Hombro}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='encogimientos', best_rep_min=10, best_rep_max=15, coaching_notes='Recorrido guiado; aprieta el trapecio un segundo arriba.' where name='Encogimientos en máquina';
update exercises_library set category='pull', movement_pattern='back_extension', primary_muscles='{Espalda}', secondary_muscles='{Glúteo,Hamstrings}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='extension_lumbar', best_rep_min=10, best_rep_max=15, coaching_notes='Sube hasta la línea del cuerpo, sin hiperextender; aprieta el glúteo arriba.' where name='Hiperextensiones en banco';
update exercises_library set category='pull', movement_pattern='hinge', primary_muscles='{Espalda}', secondary_muscles='{Hamstrings,Glúteo}', equipment='{barra}', difficulty='Avanzado', is_compound=true, tracking_type='weight_reps', substitution_group='extension_lumbar', best_rep_min=6, best_rep_max=10, coaching_notes='Barra apoyada como en sentadilla; bisagra de cadera con espalda rígida. Técnica primero, carga después.' where name='Buenos días';
update exercises_library set category='pull', movement_pattern='back_extension', primary_muscles='{Espalda}', secondary_muscles='{Glúteo}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='extension_lumbar', best_rep_min=10, best_rep_max=15, coaching_notes='Eleva brazos y piernas a la vez; pausa de un segundo arriba.' where name='Superman';

-- ── HOMBRO ───────────────────────────────────────────────────────────────────
update exercises_library set category='push', movement_pattern='vertical_push', primary_muscles='{Hombro}', secondary_muscles='{Tríceps,Core}', equipment='{barra}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='press_vertical', best_rep_min=5, best_rep_max=10, coaching_notes='Glúteo y core firmes; empuja la cabeza a través al bloquear, sin arquear la lumbar.' where name='Press militar con barra de pie';
update exercises_library set category='push', movement_pattern='vertical_push', primary_muscles='{Hombro}', secondary_muscles='{Tríceps}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='press_vertical', best_rep_min=6, best_rep_max=10, coaching_notes='Respaldo casi vertical; baja la barra a la barbilla con control.' where name='Press militar con barra sentado';
update exercises_library set category='push', movement_pattern='vertical_push', primary_muscles='{Hombro}', secondary_muscles='{Tríceps,Core}', equipment='{mancuerna}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_vertical', best_rep_min=8, best_rep_max=12, coaching_notes='De pie exige más core; sube las mancuernas en línea, no hacia delante.' where name='Press militar con mancuernas de pie';
update exercises_library set category='push', movement_pattern='vertical_push', primary_muscles='{Hombro}', secondary_muscles='{Tríceps}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_vertical', best_rep_min=8, best_rep_max=12, coaching_notes='Codos ligeramente adelante del cuerpo, no en cruz.' where name='Press militar con mancuernas sentado';
update exercises_library set category='push', movement_pattern='vertical_push', primary_muscles='{Hombro}', secondary_muscles='{Tríceps}', equipment='{maquina}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_vertical', best_rep_min=8, best_rep_max=12, coaching_notes='Ajusta el asiento para que las manos partan a la altura de las orejas.' where name='Press en máquina de hombro';
update exercises_library set category='push', movement_pattern='vertical_push', primary_muscles='{Hombro}', secondary_muscles='{Tríceps}', equipment='{smith,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_vertical', best_rep_min=6, best_rep_max=10, coaching_notes='Coloca el banco para que la barra baje justo delante de la cara.' where name='Press en Smith hombro';
update exercises_library set category='push', movement_pattern='vertical_push', primary_muscles='{Hombro}', secondary_muscles='{Pecho,Tríceps,Core}', equipment='{barra}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='press_vertical', best_rep_min=8, best_rep_max=12, coaching_notes='Empuje en diagonal, amable con el hombro; aprieta el glúteo para no compensar.' where name='Press landmine';
update exercises_library set category='push', movement_pattern='lateral_raise', primary_muscles='{Hombro}', secondary_muscles='{}', equipment='{mancuerna}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='elevacion_lateral', best_rep_min=12, best_rep_max=20, coaching_notes='Sube hasta la altura del hombro con codo suave; sin impulso del torso.' where name='Elevaciones laterales con mancuernas';
update exercises_library set category='push', movement_pattern='lateral_raise', primary_muscles='{Hombro}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='elevacion_lateral', best_rep_min=12, best_rep_max=20, coaching_notes='El cable mantiene tensión abajo, donde la mancuerna no trabaja.' where name='Elevaciones laterales en polea baja';
update exercises_library set category='push', movement_pattern='lateral_raise', primary_muscles='{Hombro}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='elevacion_lateral', best_rep_min=12, best_rep_max=20, coaching_notes='Guiada: perfecta para llegar cerca del fallo con seguridad.' where name='Elevaciones laterales en máquina';
update exercises_library set category='push', movement_pattern='front_raise', primary_muscles='{Hombro}', secondary_muscles='{}', equipment='{barra}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='elevacion_frontal', best_rep_min=10, best_rep_max=15, coaching_notes='Sube a la altura de los ojos; baja lento.' where name='Elevaciones frontales con barra';
update exercises_library set category='push', movement_pattern='front_raise', primary_muscles='{Hombro}', secondary_muscles='{}', equipment='{mancuerna}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='elevacion_frontal', best_rep_min=10, best_rep_max=15, coaching_notes='Alterna brazos si el torso empieza a balancearse.' where name='Elevaciones frontales con mancuernas';
update exercises_library set category='push', movement_pattern='front_raise', primary_muscles='{Hombro}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='elevacion_frontal', best_rep_min=10, best_rep_max=15, coaching_notes='Tensión constante; no dejes caer el cable entre reps.' where name='Elevaciones frontales en polea baja';

-- ── CUÁDRICEPS ───────────────────────────────────────────────────────────────
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo,Core}', equipment='{barra}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='sentadilla_bilateral', best_rep_min=5, best_rep_max=10, coaching_notes='Profundidad según tu movilidad; rodillas en línea con los pies y core firme.' where name='Sentadilla con barra';
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Core,Glúteo}', equipment='{barra}', difficulty='Avanzado', is_compound=true, tracking_type='weight_reps', substitution_group='sentadilla_bilateral', best_rep_min=5, best_rep_max=8, coaching_notes='Codos altos y torso vertical; castiga más el cuádriceps y exige movilidad.' where name='Sentadilla frontal';
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo}', equipment='{smith}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='sentadilla_bilateral', best_rep_min=8, best_rep_max=12, coaching_notes='Pies un paso adelante de la barra; la máquina estabiliza, tú empujas.' where name='Sentadilla en Smith';
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo,Core}', equipment='{mancuerna}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='sentadilla_bilateral', best_rep_min=8, best_rep_max=15, coaching_notes='Mancuerna al pecho; ideal para aprender el patrón de sentadilla.' where name='Sentadilla goblet';
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo}', equipment='{barra}', difficulty='Avanzado', is_compound=true, tracking_type='weight_reps', substitution_group='sentadilla_bilateral', best_rep_min=6, best_rep_max=10, coaching_notes='Barra por detrás de las piernas; torso muy vertical.' where name='Sentadilla hack con barra';
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo}', equipment='{maquina}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='sentadilla_bilateral', best_rep_min=8, best_rep_max=12, coaching_notes='Espalda pegada al respaldo; baja profundo, el rango es lo que la hace valiosa.' where name='Hack squat en máquina';
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo}', equipment='{maquina}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='prensa_pierna', best_rep_min=8, best_rep_max=15, coaching_notes='No bloquees las rodillas arriba; baja hasta donde la lumbar no se despegue.' where name='Prensa de pierna';
update exercises_library set category='legs', movement_pattern='squat', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo}', equipment='{maquina}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='prensa_pierna', best_rep_min=10, best_rep_max=15, coaching_notes='Una pierna a la vez: corrige asimetrías de fuerza.' where name='Prensa de pierna unilateral';
update exercises_library set category='legs', movement_pattern='lunge', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo,Core}', equipment='{barra}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='zancada_unilateral', best_rep_min=8, best_rep_max=12, coaching_notes='Paso largo y torso erguido; la rodilla trasera baja casi al suelo.' where name='Zancada con barra';
update exercises_library set category='legs', movement_pattern='lunge', primary_muscles='{Cuádriceps}', secondary_muscles='{Glúteo}', equipment='{mancuerna}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='zancada_unilateral', best_rep_min=8, best_rep_max=15, coaching_notes='Mancuernas a los lados; empuja con el talón delantero.' where name='Zancada con mancuernas';
update exercises_library set category='legs', movement_pattern='quad_iso', primary_muscles='{Cuádriceps}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='extension_cuadriceps', best_rep_min=10, best_rep_max=20, coaching_notes='Extiende del todo y aguanta un segundo arriba; baja lento.' where name='Extensión de cuádriceps en máquina';
update exercises_library set category='legs', movement_pattern='quad_iso', primary_muscles='{Cuádriceps}', secondary_muscles='{}', equipment='{maquina}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='extension_cuadriceps', best_rep_min=10, best_rep_max=15, coaching_notes='Unilateral: iguala la fuerza entre piernas.' where name='Extensión de cuádriceps unilateral';
update exercises_library set category='legs', movement_pattern='quad_iso', primary_muscles='{Cuádriceps}', secondary_muscles='{Core}', equipment='{peso_corporal}', difficulty='Avanzado', is_compound=false, tracking_type='reps', substitution_group='extension_cuadriceps', best_rep_min=8, best_rep_max=15, coaching_notes='Rodillas adelante y torso atrás en línea; estiramiento brutal del cuádriceps.' where name='Sissy squat';
update exercises_library set category='legs', movement_pattern='adduction', primary_muscles='{Cuádriceps}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='aduccion', best_rep_min=12, best_rep_max=20, coaching_notes='Cierra con control y resiste la apertura; no uses rebote.' where name='Aducción en máquina';

-- ── HAMSTRINGS ───────────────────────────────────────────────────────────────
update exercises_library set category='legs', movement_pattern='hinge', primary_muscles='{Hamstrings}', secondary_muscles='{Glúteo,Espalda}', equipment='{barra}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='bisagra_cadera', best_rep_min=6, best_rep_max=10, coaching_notes='Cadera atrás con espalda neutra; baja hasta sentir el estiramiento, no más.' where name='Peso muerto rumano';
update exercises_library set category='legs', movement_pattern='hinge', primary_muscles='{Hamstrings}', secondary_muscles='{Glúteo,Espalda}', equipment='{barra}', difficulty='Avanzado', is_compound=true, tracking_type='weight_reps', substitution_group='bisagra_cadera', best_rep_min=6, best_rep_max=10, coaching_notes='Piernas casi rectas: más estiramiento y más demanda lumbar; modera la carga.' where name='Peso muerto piernas rígidas';
update exercises_library set category='legs', movement_pattern='leg_curl_iso', primary_muscles='{Hamstrings}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_femoral', best_rep_min=8, best_rep_max=15, coaching_notes='Cadera pegada al banco; sube rápido, baja en 2-3 segundos.' where name='Curl femoral tumbado';
update exercises_library set category='legs', movement_pattern='leg_curl_iso', primary_muscles='{Hamstrings}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_femoral', best_rep_min=8, best_rep_max=15, coaching_notes='El sentado trabaja el femoral en más estiramiento: prioridad si puedes elegir.' where name='Curl femoral sentado';
update exercises_library set category='legs', movement_pattern='leg_curl_iso', primary_muscles='{Hamstrings}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_femoral', best_rep_min=10, best_rep_max=15, coaching_notes='Una pierna a la vez, sin arquear la lumbar.' where name='Curl femoral de pie';
update exercises_library set category='legs', movement_pattern='leg_curl_iso', primary_muscles='{Hamstrings}', secondary_muscles='{Glúteo,Core}', equipment='{peso_corporal}', difficulty='Avanzado', is_compound=false, tracking_type='reps', substitution_group='curl_femoral', best_rep_min=5, best_rep_max=10, coaching_notes='Baja lo más lento posible; empuja con las manos para volver si hace falta.' where name='Nordic curl';

-- ── GLÚTEO ───────────────────────────────────────────────────────────────────
update exercises_library set category='legs', movement_pattern='hip_extension', primary_muscles='{Glúteo}', secondary_muscles='{Hamstrings}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='empuje_cadera', best_rep_min=8, best_rep_max=12, coaching_notes='Barbilla al pecho y costillas abajo; pausa arriba apretando el glúteo.' where name='Hip thrust con barra';
update exercises_library set category='legs', movement_pattern='hip_extension', primary_muscles='{Glúteo}', secondary_muscles='{Hamstrings}', equipment='{maquina}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='empuje_cadera', best_rep_min=8, best_rep_max=15, coaching_notes='Montaje rápido y estable; ideal para progresar carga sin preparar barra.' where name='Hip thrust en máquina';
update exercises_library set category='legs', movement_pattern='hip_extension', primary_muscles='{Glúteo}', secondary_muscles='{Hamstrings}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='empuje_cadera', best_rep_min=12, best_rep_max=20, coaching_notes='Talones cerca del glúteo; sube la cadera hasta la línea del cuerpo.' where name='Glute bridge';
update exercises_library set category='legs', movement_pattern='lunge', primary_muscles='{Glúteo}', secondary_muscles='{Cuádriceps,Core}', equipment='{mancuerna,banco}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='zancada_unilateral', best_rep_min=8, best_rep_max=12, coaching_notes='Pie trasero en el banco; torso ligeramente inclinado carga más el glúteo.' where name='Zancada búlgara';
update exercises_library set category='legs', movement_pattern='lunge', primary_muscles='{Glúteo}', secondary_muscles='{Cuádriceps}', equipment='{mancuerna}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='zancada_unilateral', best_rep_min=8, best_rep_max=15, coaching_notes='El paso hacia atrás es más amable con la rodilla; empuja con el talón delantero.' where name='Zancada inversa';
update exercises_library set category='legs', movement_pattern='lunge', primary_muscles='{Glúteo}', secondary_muscles='{Cuádriceps}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='zancada_unilateral', best_rep_min=8, best_rep_max=15, coaching_notes='Sube empujando con la pierna del banco, no impulsándote con la de abajo.' where name='Step-up con mancuernas';
update exercises_library set category='legs', movement_pattern='hip_extension', primary_muscles='{Glúteo}', secondary_muscles='{Hamstrings}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='patada_gluteo', best_rep_min=12, best_rep_max=20, coaching_notes='Patada atrás con la cadera, no con la lumbar; aprieta un segundo al final.' where name='Patada de glúteo en polea';
update exercises_library set category='legs', movement_pattern='abduction', primary_muscles='{Glúteo}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='abduccion', best_rep_min=12, best_rep_max=20, coaching_notes='Inclínate ligeramente adelante para enfocar el glúteo medio.' where name='Abducción en máquina';

-- ── GEMELOS ──────────────────────────────────────────────────────────────────
update exercises_library set category='legs', movement_pattern='calf_raise', primary_muscles='{Gemelos}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='gemelos_pie', best_rep_min=8, best_rep_max=15, coaching_notes='Pausa de 1-2 segundos abajo en estiramiento; sube alto sin rebotar. Con máquina o mancuerna si necesitas carga.' where name='Elevación de talones de pie';
update exercises_library set category='legs', movement_pattern='calf_raise', primary_muscles='{Gemelos}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='gemelos_pie', best_rep_min=10, best_rep_max=15, coaching_notes='Rango completo en la prensa; controla la bajada.' where name='Elevación de talones en prensa';
update exercises_library set category='legs', movement_pattern='calf_raise', primary_muscles='{Gemelos}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='gemelos_sentado', best_rep_min=12, best_rep_max=20, coaching_notes='Sentado trabaja el sóleo; tolera más repeticiones.' where name='Elevación de talones sentado';

-- ── BÍCEPS ───────────────────────────────────────────────────────────────────
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{barra}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_biceps_barra', best_rep_min=8, best_rep_max=12, coaching_notes='Codos pegados al torso; sin balanceo de cadera.' where name='Curl con barra recta';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{barra}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_biceps_barra', best_rep_min=8, best_rep_max=12, coaching_notes='El agarre en W cuida las muñecas; misma regla, codos quietos.' where name='Curl con barra EZ';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{mancuerna}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_biceps_mancuerna', best_rep_min=8, best_rep_max=15, coaching_notes='Supina la muñeca al subir; baja en 2-3 segundos.' where name='Curl con mancuernas de pie';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_biceps_mancuerna', best_rep_min=8, best_rep_max=15, coaching_notes='Sentado elimina el impulso; el bíceps hace todo el trabajo.' where name='Curl con mancuernas sentado';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{mancuerna,banco}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='curl_biceps_mancuerna', best_rep_min=8, best_rep_max=12, coaching_notes='El respaldo inclinado estira el bíceps abajo: el mejor rango de todos los curls.' where name='Curl inclinado con mancuernas';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{mancuerna}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_martillo', best_rep_min=8, best_rep_max=15, coaching_notes='Agarre neutro: braquial y antebrazo; suele permitir algo más de peso.' where name='Curl martillo';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{barra,banco}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_predicador', best_rep_min=8, best_rep_max=12, coaching_notes='El banco fija el brazo: cero trampa; no extiendas del todo con mucha carga.' where name='Curl predicador con barra EZ';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_predicador', best_rep_min=8, best_rep_max=12, coaching_notes='Un brazo a la vez; controla especialmente la bajada.' where name='Curl predicador con mancuerna';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{maquina}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_predicador', best_rep_min=10, best_rep_max=15, coaching_notes='Guiado y estable; perfecto para las últimas series al fallo.' where name='Curl en máquina';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='curl_polea', best_rep_min=10, best_rep_max=15, coaching_notes='Tensión constante en todo el recorrido, también abajo.' where name='Curl en polea baja';
update exercises_library set category='pull', movement_pattern='curl', primary_muscles='{Bíceps}', secondary_muscles='{}', equipment='{polea}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='curl_polea', best_rep_min=10, best_rep_max=15, coaching_notes='Brazos en cruz a la altura del hombro; pico de contracción brutal.' where name='Curl en polea alta';

-- ── TRÍCEPS ──────────────────────────────────────────────────────────────────
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='ext_triceps_polea', best_rep_min=10, best_rep_max=15, coaching_notes='Codos fijos al costado; abre la cuerda al final para contraer más.' where name='Extensión en polea alta con cuerda';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='ext_triceps_polea', best_rep_min=10, best_rep_max=15, coaching_notes='La barra permite algo más de carga que la cuerda; codos quietos.' where name='Extensión en polea alta con barra';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{polea}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='ext_triceps_polea', best_rep_min=10, best_rep_max=15, coaching_notes='Por encima de la cabeza: trabaja la cabeza larga en estiramiento.' where name='Extensión en polea baja';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='ext_triceps_polea', best_rep_min=12, best_rep_max=15, coaching_notes='Un brazo a la vez; útil para igualar fuerza entre lados.' where name='Extensión unilateral en polea';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{polea}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='ext_triceps_polea', best_rep_min=10, best_rep_max=15, coaching_notes='Desde polea baja por detrás de la cabeza; gran estiramiento de la cabeza larga.' where name='Katanas en polea baja';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Tríceps}', secondary_muscles='{Pecho,Hombro}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=true, tracking_type='weight_reps', substitution_group='press_cerrado', best_rep_min=6, best_rep_max=10, coaching_notes='Agarre al ancho de hombros, codos pegados; el press pesado del tríceps.' where name='Press cerrado con barra';
update exercises_library set category='push', movement_pattern='horizontal_push', primary_muscles='{Tríceps}', secondary_muscles='{Pecho,Hombro}', equipment='{smith,banco}', difficulty='Principiante', is_compound=true, tracking_type='weight_reps', substitution_group='press_cerrado', best_rep_min=8, best_rep_max=12, coaching_notes='Trayectoria guiada; codos cerca del torso al bajar.' where name='Press cerrado en Smith';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='frances_skull', best_rep_min=8, best_rep_max=12, coaching_notes='Baja la barra a la frente o detrás; codos apuntando al techo.' where name='Press francés con barra EZ tumbado';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{mancuerna,banco}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='frances_skull', best_rep_min=8, best_rep_max=12, coaching_notes='Una mancuerna con ambas manos o una por brazo; controla el recorrido.' where name='Press francés con mancuerna tumbado';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{mancuerna,banco}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='frances_skull', best_rep_min=8, best_rep_max=12, coaching_notes='Por encima de la cabeza sentado; la cabeza larga trabaja en máximo estiramiento.' where name='Press francés con mancuernas sentado';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{barra,banco}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='frances_skull', best_rep_min=8, best_rep_max=12, coaching_notes='Codos quietos apuntando al techo; si duelen, cambia a polea.' where name='Skull crusher con barra EZ';
update exercises_library set category='push', movement_pattern='triceps_extension', primary_muscles='{Tríceps}', secondary_muscles='{}', equipment='{mancuerna,banco}', difficulty='Intermedio', is_compound=false, tracking_type='weight_reps', substitution_group='frances_skull', best_rep_min=8, best_rep_max=12, coaching_notes='Agarre neutro, más amable con el codo que la barra.' where name='Skull crusher con mancuernas';
update exercises_library set category='push', movement_pattern='dip', primary_muscles='{Tríceps}', secondary_muscles='{Pecho,Hombro}', equipment='{banco}', difficulty='Principiante', is_compound=true, tracking_type='reps', substitution_group='fondos_triceps', best_rep_min=10, best_rep_max=20, coaching_notes='Cadera cerca del banco y hombros abajo; si molesta el hombro, reduce el rango.' where name='Fondos en banco';
update exercises_library set category='push', movement_pattern='dip', primary_muscles='{Tríceps}', secondary_muscles='{Pecho,Hombro}', equipment='{peso_corporal,barra_dominadas}', difficulty='Intermedio', is_compound=true, tracking_type='reps', substitution_group='fondos_triceps', best_rep_min=6, best_rep_max=12, coaching_notes='Torso vertical y codos pegados para cargar el tríceps.' where name='Fondos en paralelas tríceps';

-- ── CORE ─────────────────────────────────────────────────────────────────────
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='time', substitution_group='plancha', best_rep_min=20, best_rep_max=60, coaching_notes='Glúteo apretado y lumbar neutra; no dejes caer la cadera.' where name='Plancha frontal';
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{Hombro}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='time', substitution_group='plancha', best_rep_min=20, best_rep_max=45, coaching_notes='Cuerpo en línea de lado; la cadera no se hunde.' where name='Plancha lateral';
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{Hombro}', equipment='{peso_corporal}', difficulty='Intermedio', is_compound=false, tracking_type='time', substitution_group='plancha', best_rep_min=20, best_rep_max=45, coaching_notes='Extiende el brazo sin rotar la cadera; el reto es no moverse.' where name='Plancha con elevación de brazo';
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='core_control', best_rep_min=10, best_rep_max=16, coaching_notes='Lumbar pegada al suelo mientras bajas brazo y pierna contrarios.' where name='Dead bug';
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{Glúteo}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='core_control', best_rep_min=10, best_rep_max=16, coaching_notes='Extiende brazo y pierna contrarios sin arquear la lumbar.' where name='Bird dog';
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{Hombro}', equipment='{rueda_abs}', difficulty='Avanzado', is_compound=false, tracking_type='reps', substitution_group='ab_rollout', best_rep_min=6, best_rep_max=12, coaching_notes='Rueda hasta donde controles la lumbar; empieza desde rodillas.' where name='Ab wheel';
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Intermedio', is_compound=false, tracking_type='time', substitution_group='core_control', best_rep_min=20, best_rep_max=45, coaching_notes='Lumbar presionada contra el suelo; brazos y piernas estirados.' where name='Hollow body hold';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal,banco}', difficulty='Avanzado', is_compound=false, tracking_type='reps', substitution_group='elevacion_piernas', best_rep_min=5, best_rep_max=10, coaching_notes='Baja el cuerpo recto lo más lento posible; ejercicio de control total.' where name='Dragon flag';
update exercises_library set category='core', movement_pattern='core_anti_extension', primary_muscles='{Core}', secondary_muscles='{Hombro}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='plancha', best_rep_min=20, best_rep_max=40, coaching_notes='Cadera baja y estable; alterna rodillas al pecho con ritmo.' where name='Mountain climbers';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='crunch', best_rep_min=12, best_rep_max=20, coaching_notes='Despega solo la parte alta de la espalda; exhala al subir.' where name='Crunch tradicional';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='elevacion_piernas', best_rep_min=12, best_rep_max=20, coaching_notes='Lleva las rodillas al pecho despegando la cadera del suelo.' where name='Crunch inverso';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='crunch', best_rep_min=10, best_rep_max=15, coaching_notes='De rodillas frente a la polea; flexiona el torso, no jales con los brazos. El crunch con carga progresiva.' where name='Crunch en polea';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='crunch', best_rep_min=12, best_rep_max=20, coaching_notes='Sube completo con control; si tira la cadera, vuelve al crunch.' where name='Sit-up';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='elevacion_piernas', best_rep_min=10, best_rep_max=20, coaching_notes='Lumbar pegada al suelo; baja las piernas solo hasta donde la mantengas.' where name='Elevación de piernas tumbado';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{Espalda}', equipment='{barra_dominadas}', difficulty='Intermedio', is_compound=false, tracking_type='reps', substitution_group='elevacion_piernas', best_rep_min=8, best_rep_max=15, coaching_notes='Piernas rectas hasta la horizontal sin balancearte.' where name='Elevación de piernas en barra';
update exercises_library set category='core', movement_pattern='core_flexion', primary_muscles='{Core}', secondary_muscles='{Espalda}', equipment='{barra_dominadas}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='elevacion_piernas', best_rep_min=10, best_rep_max=15, coaching_notes='Rodillas al pecho con control; progresión hacia piernas rectas.' where name='Rodillas al pecho en barra';
update exercises_library set category='core', movement_pattern='core_rotation', primary_muscles='{Core}', secondary_muscles='{}', equipment='{peso_corporal}', difficulty='Principiante', is_compound=false, tracking_type='reps', substitution_group='rotacion', best_rep_min=16, best_rep_max=30, coaching_notes='Rota el torso, no solo los brazos; añade peso cuando sea fácil.' where name='Russian twist';
update exercises_library set category='core', movement_pattern='core_rotation', primary_muscles='{Core}', secondary_muscles='{Hombro}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='rotacion', best_rep_min=10, best_rep_max=15, coaching_notes='De arriba hacia abajo en diagonal; gira desde la cadera con brazos firmes.' where name='Woodchop en polea alta';
update exercises_library set category='core', movement_pattern='core_rotation', primary_muscles='{Core}', secondary_muscles='{Hombro}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='rotacion', best_rep_min=10, best_rep_max=15, coaching_notes='De abajo hacia arriba; el movimiento nace del core, no de los brazos.' where name='Woodchop en polea baja';
update exercises_library set category='core', movement_pattern='core_rotation', primary_muscles='{Core}', secondary_muscles='{}', equipment='{polea}', difficulty='Principiante', is_compound=false, tracking_type='weight_reps', substitution_group='antirotacion', best_rep_min=10, best_rep_max=15, coaching_notes='Extiende los brazos y resiste el giro; anti-rotación pura.' where name='Pallof press';
update exercises_library set category='core', movement_pattern='core_carry', primary_muscles='{Core}', secondary_muscles='{Espalda,Hombro}', equipment='{mancuerna}', difficulty='Principiante', is_compound=true, tracking_type='time', substitution_group='cargas', best_rep_min=30, best_rep_max=60, coaching_notes='Camina erguido con carga pesada a ambos lados; hombros atrás.' where name='Farmer carry';
update exercises_library set category='core', movement_pattern='core_carry', primary_muscles='{Core}', secondary_muscles='{Espalda,Hombro}', equipment='{mancuerna}', difficulty='Principiante', is_compound=true, tracking_type='time', substitution_group='cargas', best_rep_min=30, best_rep_max=60, coaching_notes='Carga a un solo lado sin inclinarte; el core resiste la flexión lateral.' where name='Suitcase carry';

-- =============================================================================
-- VERIFICACIÓN (ejecutar tras aplicar; deben devolver 0 filas / valores esperados)
-- =============================================================================
-- select count(*) from exercises_library where is_active and (category is null
--   or movement_pattern is null or primary_muscles is null or equipment is null
--   or difficulty is null or is_compound is null or tracking_type is null
--   or substitution_group is null or best_rep_min is null or best_rep_max is null
--   or coaching_notes is null);                                      -- → 0
-- select distinct category from exercises_library;                    -- 4 valores
-- select distinct difficulty from exercises_library;                  -- 3 niveles
-- select name from exercises_library where primary_muscles[1] <> muscle_group; -- → 0 filas
